version: "3.9"

services:
  kolibri:
    build:
      context: https://github.com/LotsaGeese/my-server/kolibri.git#main
      dockerfile: Dockerfilekolibri
    container_name: kolibri_test
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - kolibri_data:/kolibri/.kolibri

volumes:
  kolibri_data:
